### PR TITLE
refactor: array loop to Array.forEach

### PR DESCRIPTION
**Pull request by curbengh**

### CODE REVIEW

**Comment by curbengh** [comment]
initially, I wanted to
```js
const result = languages.map(...)
```
but I don't know exactly how to return object `{ [key]: data[lang][key] }`.

**Comment by segayuu** [comment]
The following is my own opinion.
`Array.prototype.forEach()` looks beautiful because it eliminates some of the temporary variables, but I do not think that it will have a very good effect except for it.
When trying to break a loop, `Array#forEach()` has no way to do it (except to throw an exception) and needs to rewrite the whole loop.
Also, compared with `Array#map()` and `Array#filter()`, it does not make clearer intention than for loop.

**Comment by segayuu** [comment]
[I know that we can assign from an array to an object by using Array#reduce()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#Counting_instances_of_values_in_an_object).
I like Array#reduce(), but like Array#forEach(), can write approximate content, so some people may not like it.

**Comment by curbengh** [comment]
I see. `forEach()` cannot do `if (!langData) continue;`. What about the refactor in line 63? It doesn't seem have a need to break a loop.

**Comment by segayuu** [comment]
@curbengh Your opinion is correct.
In fact, the reason for not merging this PR is just my religious and coding guide.
I personally will not merge this PR, but I think that it may be merged upon review by other people :)

**Comment by curbengh** [comment]
added another check.

**Pull request merged**
